"""
Probability distribution function of epsilon = l/A (see paper)  from Gadget-4 simulations. Uses the
files generated by generate_beta_l_ta.py.

Usage
-----
    python pdf_l_ta.py
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib
from scipy.integrate import quad
import units as u

from pdf_beta_ta import g_numeric

matplotlib.rcParams['text.latex.preamble'] = r'\usepackage{mathpazo}'
plt.rcParams['axes.linewidth'] = 2
plt.rc('text', usetex=True)
plt.rc('font', family='serif')


def compute_epsilon(mr):
    """
    Compute epsilon = l/A from simulation data.

    """
    l_sim = np.load(f"l_sim_min_{mr}.npy")
    r_in = np.load(f"r_in_{mr}.npy")
    r_closest = np.load(f"r_closest_{mr}.npy")
    Npart = len(l_sim)
    mH = u.Msun
    mL = mr * mH
    L = 1e-2 * u.pc
    Vtilde = 4 * np.pi * (L ** (3 - 9 / 4)) / (3 - 9 / 4)
    ntilde = Npart / Vtilde
    epsilon_vals = []
    A_vals = []
    for i in range(Npart):
        rin = r_in[i]
        rmin = r_closest[i]
        l = l_sim[i]
        if rmin <= 0 or rmin >= rin or l <= 0:
            continue
        eps_orbit = rmin / rin
        # characteristic torque
        tau_c = 2.6 * u.G * mL ** 2 * ntilde ** (2 / 3) * rin ** (-0.5)
        # Integral I(alpha, eps)
        I_val = quad(lambda u: u ** 0.5 * (1 - u) ** (-0.5), eps_orbit, 1.0)[0]
        # A coefficient
        A = (1 / (np.sqrt(2 * u.G * mH) * mL)) * tau_c * rin ** (3 / 2) * I_val
        if A > 0:
            epsilon_vals.append(l / A)
            A_vals.append(A)
    return np.array(epsilon_vals), np.array(A_vals)

def plot_epsilon_distribution(mr):
    """
    Generate and save histogram of epsilon distribution vs analytical prediction.
    
    """
    epsilon_vals, A_vals = compute_epsilon(mr)
    # Histogram of epsilon
    epsmax = 10
    nbins = 120
    eps_vals = epsilon_vals[epsilon_vals <= epsmax]
    bins = np.linspace(eps_vals.min(), eps_vals.max(), nbins)
    epsl = np.linspace(0, epsmax, 100)
    g_vals = np.array([g_numeric(eps) for eps in epsl])
    hist, bin_edges = np.histogram(eps_vals, bins=bins, density=True)
    # Plot
    fig, ax = plt.subplots(figsize=(10, 8), constrained_layout=True)
    ax.step(bin_edges[:-1], hist, where='post', linewidth=2, color="royalblue", label="Simulated")
    plt.plot(epsl, g_vals, lw=2.5, color="crimson", label="Analytical")
    plt.xlabel(r"$\epsilon = \ell / \mathcal{A}$", fontsize=20)
    plt.ylabel(r"$\mathcal P (\ell / \mathcal{A})$", fontsize=20)
    ax.tick_params(which='major', direction='in', width=2, length=10, top=True, right=True, labelsize=18)
    ax.tick_params(which='minor', direction='in', width=1, length=7, top=True, right=True, pad=11)
    ax.set_title(f"$m_r = 10^{{{np.log10(mr):.0f}}}$", fontsize=21)
    plt.xlim(0, 10)
    plt.ylim(0, 0.5)
    plt.legend(frameon=False, fontsize=15)
    plt.savefig("epsilon_distribution.pdf", dpi=300)

    return


if __name__ == "__main__":
     mr = 1e-5
     plot_epsilon_distribution(mr)
