"""
Probability distribution function of beta = tau_i / tau_c from Gadget-4 simulations. Uses the
files generated by generate_beta_l_ta.py.

Usage
-----
    python pdf_beta_ta.py
"""

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from scipy.integrate import quad
from scipy.special import j0

matplotlib.rcParams["text.latex.preamble"] = r"\usepackage{mathpazo}"
plt.rcParams["axes.linewidth"] = 2
plt.rc("text", usetex=True)
plt.rc("font", family="serif")


def g_numeric(gamma: float) -> float:
    """
    Compute the analytical distribution of beta from torque statistics.
    
    """
    f = lambda s: s * j0(s * gamma) * np.exp(-s ** (3 / 2))
    I, _ = quad(f, 0, np.inf)
    return gamma * I


def generate_beta_plot(mr: float) -> None:
    """
    Generate and save histogram of beta simulated distribution vs analytical prediction.
  
    """
    beta_p = np.load(f"beta_in_{mr}_new.npy")

    beta_max_plot = 10
    mask = beta_p <= beta_max_plot

    n_total = len(beta_p)
    n_kept = int(np.sum(mask))
    n_removed = n_total - n_kept

    print(f"Keeping {n_kept}/{n_total} particles")
    print(f"Removed {n_removed} particles with beta > {beta_max_plot}")

    beta_plot = beta_p[mask]

    nbins = 200
    bins = np.linspace(beta_plot.min(), beta_plot.max(), nbins)
    betas = np.linspace(0, beta_max_plot, 100)
    numerical = np.array([g_numeric(beta) for beta in betas])

    hist, bin_edges = np.histogram(beta_plot, bins=bins, density=True)

    fig, ax = plt.subplots(constrained_layout=True, figsize=(10, 8))
    ax.step(bin_edges[:-1], hist, where="post", linewidth=2, color="royalblue", label="Simulated")
    ax.plot(betas, numerical, lw=2, color="crimson", label="Analytical")

    ax.set_xlabel(r"$\beta$", fontsize=20)
    ax.set_ylabel(r"$\mathcal P (\beta)$", fontsize=20)

    ax.tick_params(which="major", direction="in", width=2, length=10, top=True, right=True, labelsize=18, pad=11)
    ax.tick_params(which="minor", direction="in", width=1, length=7, top=True, right=True, pad=11)
    ax.set_xlim(0, 10)

    ax.set_xlim(0, 10)
    ax.set_ylim(0, 0.5)
    ax.set_title(f"$m_r = 10^{{{np.log10(mr):.0f}}}$", fontsize=21)
    ax.legend(frameon=False, fontsize=15)

    plt.savefig(f"beta_distribution_{mr}.pdf")
    plt.savefig(f"beta_distribution_{mr}.png", dpi=300)



if __name__ == "__main__":
    generate_beta_plot(1e-5)